---
- hosts: localhost
  vars:
    not_disks:
      - disk: 1
        letter: D
        name: data
      - disk: 2
        letter: L
        name: log
      - disk: 3
        letter: T
        name: pizza
  roles:
    - role: disk-management
      vars:
        disks: "{{ not_disks }}"
